import type {Metadata} from "next";
import {Space_Mono} from "next/font/google";
import "./globals.css";

const spaceMono = Space_Mono({
	display: "swap",
	subsets: ["latin"],
	style: ["normal", "italic"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Tip Calculator",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en-US">
			<body className={`${spaceMono.className}`}>{children}</body>
		</html>
	);
};

export default RootLayout;
