import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Tip Calculator",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en-US">
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
